###REST Client


### LOGIN
POST https://tb.geati.camboriu.ifc.edu.br/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username":"tenant@thingsboard.org",
    "password":"tenant"
}

###keys
GET https://tb.geati.camboriu.ifc.edu.br/api/plugins/telemetry/DEVICE/2b03c3d0-5719-11ee-bdd4-b1244f07481c/keys/attributes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwidXNlcklkIjoiMjEwM2I5YTAtNTM1Mi0xMWVlLWE1OGMtNTU5YjU0MjI5MGMzIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJzZXNzaW9uSWQiOiJjYjVmY2MxNy05ODM0LTRkYTQtOTI0Mi0wODIxMTQxMzAzYmUiLCJpc3MiOiJ0aGluZ3Nib2FyZC5pbyIsImlhdCI6MTcyNTM4NzMzNiwiZXhwIjoxNzI1Mzk2MzM2LCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiMjA0Zjg0ZDAtNTM1Mi0xMWVlLWE1OGMtNTU5YjU0MjI5MGMzIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCJ9.J79g5TzD2tzyrwLz7TF84SKyFFJld4fobzLbrXgKxNR_XoEuSMOJGUY5JcZOkZ3a12YzptKyEngRxQsAKu8t-Q

###timeseries
GET https://tb.geati.camboriu.ifc.edu.br/api/plugins/telemetry/DEVICE/2b03c3d0-5719-11ee-bdd4-b1244f07481c/keys/timeseries HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwidXNlcklkIjoiMjEwM2I5YTAtNTM1Mi0xMWVlLWE1OGMtNTU5YjU0MjI5MGMzIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJzZXNzaW9uSWQiOiJjYjVmY2MxNy05ODM0LTRkYTQtOTI0Mi0wODIxMTQxMzAzYmUiLCJpc3MiOiJ0aGluZ3Nib2FyZC5pbyIsImlhdCI6MTcyNTM4NzMzNiwiZXhwIjoxNzI1Mzk2MzM2LCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiMjA0Zjg0ZDAtNTM1Mi0xMWVlLWE1OGMtNTU5YjU0MjI5MGMzIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCJ9.J79g5TzD2tzyrwLz7TF84SKyFFJld4fobzLbrXgKxNR_XoEuSMOJGUY5JcZOkZ3a12YzptKyEngRxQsAKu8t-Q

###timeseries-data
GET https://tb.geati.camboriu.ifc.edu.br/api/plugins/telemetry/DEVICE/2b03c3d0-5719-11ee-bdd4-b1244f07481c/values/timeseries?keys=temperatura%2Chumidade%2Ccalor%2Ctemperatura2%2Chumidade2%2Ccalor2&startTs=0&endTs=1725387641000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZW5hbnRAdGhpbmdzYm9hcmQub3JnIiwidXNlcklkIjoiMjEwM2I5YTAtNTM1Mi0xMWVlLWE1OGMtNTU5YjU0MjI5MGMzIiwic2NvcGVzIjpbIlRFTkFOVF9BRE1JTiJdLCJzZXNzaW9uSWQiOiJjYjVmY2MxNy05ODM0LTRkYTQtOTI0Mi0wODIxMTQxMzAzYmUiLCJpc3MiOiJ0aGluZ3Nib2FyZC5pbyIsImlhdCI6MTcyNTM4NzMzNiwiZXhwIjoxNzI1Mzk2MzM2LCJlbmFibGVkIjp0cnVlLCJpc1B1YmxpYyI6ZmFsc2UsInRlbmFudElkIjoiMjA0Zjg0ZDAtNTM1Mi0xMWVlLWE1OGMtNTU5YjU0MjI5MGMzIiwiY3VzdG9tZXJJZCI6IjEzODE0MDAwLTFkZDItMTFiMi04MDgwLTgwODA4MDgwODA4MCJ9.J79g5TzD2tzyrwLz7TF84SKyFFJld4fobzLbrXgKxNR_XoEuSMOJGUY5JcZOkZ3a12YzptKyEngRxQsAKu8t-Q